In [542]:
import numpy as np
import pandas as pd

df = pd.read_csv('Data_Train.csv')
df.head()

STORY  SECTION
0  But the most painful was the huge reversal in ...        3
1  How formidable is the opposition alliance amon...        0
2  Most Asian currencies were trading lower today...        3
3  If you want to answer any question, click on ‘...        1
4  In global markets, gold prices edged up today ...        3

In [516]:
df['STORY'][1]

'opposition alliance Congress Jharkhand Mukti Morcha JMM Jharkhand Vikas Morcha Prajatantrik'

In [ ]:
for j in range(len(df)):
    n = [token for token in nlp(df['STORY'][j]) if token.pos_=='NOUN' or token.pos_=='PROPN']
    text=''
    for i in range(len(n)):
        text=text+' '+str(n[i])
    text=text[1:]
    df['STORY'][j]=text
    print(j)
df.head()

In [ ]:
df.isnull().sum()

In [ ]:
blanks = []  # start with an empty list

for i,lb,rv in df.itertuples():  # iterate over the DataFrame
    if type(rv)==str:            # avoid NaN values
        if rv.isspace():         # test 'review' for whitespace
            blanks.append(i)     # add matching index numbers to the list
        
print(len(blanks), 'blanks: ', blanks)

In [ ]:
df['SECTION'].value_counts()

In [ ]:
from sklearn.model_selection import train_test_split

X = df['STORY']
y = df.iloc[:, 1].values

y=y.reshape(y.shape[0],1)
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features = [0])
y = onehotencoder.fit_transform(y).toarray()


In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC

# Naïve Bayes:
text_clf_nb = Pipeline([('tfidf', TfidfVectorizer()),
                     ('clf', MultinomialNB()),
])

# Linear SVC:
text_clf_lsvc = Pipeline([('tfidf', TfidfVectorizer()),
                     ('clf', LinearSVC()),
])

In [ ]:
text_clf_nb.fit(X_train, y_train)

In [ ]:
predictions = text_clf_nb.predict(X_test)

In [ ]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test,predictions))

In [ ]:
print(metrics.classification_report(y_test,predictions))

In [ ]:
print(metrics.accuracy_score(y_test,predictions))

In [ ]:
stopwords = ['a', 'about', 'above', 'across', 'after', 'afterwards', 'again', 'against', 'all', 'almost', 'alone', 'along', 'already', 'also', 'although', 'always', 'am', 'among', 'amongst', 'amoungst', 'amount', 'an', 'and', 'another', 'any', 'anyhow', 'anyone', 'anything', 'anyway', 'anywhere', 'are', 'around', 'as', 'at', 'back', 'be', 'became', 'because', 'become', 'becomes', 'becoming', 'been', 'before', 'beforehand', 'behind', 'being', 'below', 'beside', 'besides', 'between', 'beyond', 'bill', 'both', 'bottom', 'but', 'by', 'call', 'can', 'cannot', 'cant', 'co', 'con', 'could', 'couldnt', 'cry', 'de', 'describe', 'detail', 'do', 'done', 'down', 'due', 'during', 'each', 'eg', 'eight', 'either', 'eleven', 'else', 'elsewhere', 'empty', 'enough', 'etc', 'even', 'ever', 'every', 'everyone', 'everything', 'everywhere', 'except', 'few', 'fifteen', 'fifty', 'fill', 'find', 'fire', 'first', 'five', 'for', 'former', 'formerly', 'forty', 'found', 'four', 'from', 'front', 'full', 'further', 'get', 'give', 'go', 'had', 'has', 'hasnt', 'have', 'he', 'hence', 'her', 'here', 'hereafter', 'hereby', 'herein', 'hereupon', 'hers', 'herself', 'him', 'himself', 'his', 'how', 'however', 'hundred', 'i', 'ie', 'if', 'in', 'inc', 'indeed', 'interest', 'into', 'is', 'it', 'its', 'itself', 'keep', 'last', 'latter', 'latterly', 'least', 'less', 'ltd', 'made', 'many', 'may', 'me', 'meanwhile', 'might', 'mill', 'mine', 'more', 'moreover', 'most', 'mostly', 'move', 'much', 'must', 'my', 'myself', 'name', 'namely', 'neither', 'never', 'nevertheless', 'next', 'nine', 'no', 'nobody', 'none', 'noone', 'nor', 'not', 'nothing', 'now', 'nowhere', 'of', 'off', 'often', 'on', 'once', 'one', 'only', 'onto', 'or', 'other', 'others', 'otherwise', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 'part', 'per', 'perhaps', 'please', 'put', 'rather', 're', 'same', 'see', 'seem', 'seemed', 'seeming', 'seems', 'serious', 'several', 'she', 'should', 'show', 'side', 'since', 'sincere', 'six', 'sixty', 'so', 'some', 'somehow', 'someone', 'something', 'sometime', 'sometimes', 'somewhere', 'still', 'such', 'system', 'take', 'ten', 'than', 'that', 'the', 'their', 'them', 'themselves', 'then', 'thence', 'there', 'thereafter', 'thereby', 'therefore', 'therein', 'thereupon', 'these', 'they', 'thick', 'thin', 'third', 'this', 'those', 'though', 'three', 'through', 'throughout', 'thru', 'thus', 'to', 'together', 'too', 'top', 'toward', 'towards', 'twelve', 'twenty', 'two', 'un', 'under', 'until', 'up', 'upon', 'us', 'very', 'via', 'was', 'we', 'well', 'were', 'what', 'whatever', 'when', 'whence', 'whenever', 'where', 'whereafter', 'whereas', 'whereby', 'wherein', 'whereupon', 'wherever', 'whether', 'which', 'while', 'whither', 'who', 'whoever', 'whole', 'whom', 'whose', 'why', 'will', 'with', 'within', 'without', 'would', 'yet', 'you', 'your', 'yours', 'yourself', 'yourselves']

In [ ]:
# YOU DO NOT NEED TO RUN THIS CELL UNLESS YOU HAVE
# RECENTLY OPENED THIS NOTEBOOK OR RESTARTED THE KERNEL:

import numpy as np
import pandas as pd

df = pd.read_csv('Data_Train.csv')
df.dropna(inplace=True)
blanks = []
for i,lb,rv in df.itertuples():
    if type(rv)==str:
        if rv.isspace():
            blanks.append(i)
df.drop(blanks, inplace=True)
from sklearn.model_selection import train_test_split
X = df['STORY']
y = df['SECTION']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

In [ ]:
text_clf_lsvc2 = Pipeline([('tfidf', TfidfVectorizer(tokenizer=Tokenizer,stop_words=stopwords)),('clf',  RandomForestClassifier()),
])
text_clf_lsvc2.fit(X_train, y_train)

In [342]:
from sklearn.base import BaseEstimator, TransformerMixin
class TextSelector(BaseEstimator, TransformerMixin):
    def __init__(self, field):
        self.field = field
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        return X[self.field]
    
class NumberSelector(BaseEstimator, TransformerMixin):
    def __init__(self, field):
        self.field = field
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        return X[[self.field]]

In [429]:
import nltk
from nltk.stem import WordNetLemmatizer 
lemmatizer = WordNetLemmatizer()
import re
def Tokenizer(str_input):
    words = re.sub(r"[^A-Za-z0-9\-]", " ", str_input).lower().split()
    porter_stemmer=nltk.PorterStemmer()
    words = [lemmatizer.lemmatize(word) for word in words]
    return words

In [370]:
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import TruncatedSVD
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
text_clf_rf = Pipeline([
    ('features', FeatureUnion([
        ('text', Pipeline([
            ('colext', TextSelector(df['STORY'])),
            ('tfidf', TfidfVectorizer(tokenizer=Tokenizer, stop_words=stop_words,
                     min_df=.0025, max_df=0.25, ngram_range=(1,3))),
            ('svd', TruncatedSVD(algorithm='randomized', n_components=300)), #for XGB
        ])),
        ('words', Pipeline([
            ('wordext', NumberSelector('TotalWords')),
            ('wscaler', StandardScaler()),
        ])),
    ])),
    ('clf', XGBClassifier(max_depth=3, n_estimators=300, learning_rate=0.1)),
   #('clf', RandomForestClassifier()),
    ])
text_clf_rf.fit(X_train, y_train)

C:\Users\dell\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:301: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['abov', 'ani', 'becaus', 'befor', 'doe', 'dure', 'ha', 'hi', 'onc', 'onli', 'ourselv', 'themselv', 'thi', 'veri', 'wa', 'whi', 'yourselv'] not in stop_words.
  'stop_words.' % sorted(inconsistent))


ValueError: np.nan is an invalid document, expected byte or unicode string.

In [436]:
predictions1 = text_clf_lsvc2.predict(X_test)
#predictions2 = text_clf_nb.predict(X_test)
print(metrics.confusion_matrix(y_test,predictions1))

[[446  19  12  14]
 [ 10 795  24  17]
 [ 15  20 561   2]
 [  8  37  11 298]]


In [437]:
print(metrics.classification_report(y_test,predictions1))

              precision    recall  f1-score   support

           0       0.93      0.91      0.92       491
           1       0.91      0.94      0.93       846
           2       0.92      0.94      0.93       598
           3       0.90      0.84      0.87       354

   micro avg       0.92      0.92      0.92      2289
   macro avg       0.92      0.91      0.91      2289
weighted avg       0.92      0.92      0.92      2289



In [438]:
print(metrics.accuracy_score(y_test,predictions1))

0.9174311926605505


In [318]:
pred=pd.DataFrame(predictions1)
act=pd.DataFrame(y_test)
pd.concat(pred,act)

TypeError: first argument must be an iterable of pandas objects, you passed an object of type "DataFrame"

In [310]:
df = pd.read_csv('Data_Test.csv')
from sklearn.model_selection import train_test_split
X2 = df['STORY']

In [311]:
#text_clf_lsvc2 = Pipeline([('tfidf', TfidfVectorizer(stop_words=stopwords)),
 #                    ('clf', MultinomialNB()),
#])
text_clf_rf.fit(X, y)

Pipeline(memory=None,
     steps=[('tfidf', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,...0,
     multi_class='crammer_singer', penalty='l2', random_state=None,
     tol=0.0001, verbose=0))])

In [312]:
predictions = text_clf_rf.predict(X2)
predictions

array([1, 2, 1, ..., 1, 0, 1], dtype=int64)

In [313]:
ans = pd.DataFrame({'SECTION': predictions})

In [314]:
writer = pd.ExcelWriter('new.xlsx', engine='xlsxwriter')

# Convert the dataframe to an XlsxWriter Excel object.
ans.to_excel(writer, sheet_name='Sheet1')

# Close the Pandas Excel writer and output the Excel file.
writer.save()

### New

In [541]:
df

STORY
0     gadgets smartphones devices user experience le...
1     wave future lot diversity representation phase...
2     smartphone strengths smartphones performance c...
3     application dashboard cases beneficiary panel ...
4     gadgets consumers experts tech industry smartp...
5     message record fact record phone number place ...
6     sensors buttons buttons gamepad phone storage ...
7     fact film school thing ideas life choices kids...
8           button something button controls icon label
9     moves spear lightning everyone hands thing pur...
10    leadership pressure generation constituencies ...
11    volume lakh shares company crore day clarifica...
12                                           board film
13    phone camera lens camera camera clicker phone ...
14       pressure point house hole actor end day mother
15    storage series listing smartphone certificatio...
16    telecom industry broadband subscribers growth ...
17       finale performances coaches milao medley songs
18    slew market months resources monetization rent...
19    report record RMB record collection fans parts...
20    Lannister riders men families anguish terror l...
21    hatred show message revenge answer everything ...
22    film summer dollars box office record dollars ...
23    potshots weeks campaign trail part 1990s colli...
24    authorities day night people jail Nobody valid...
25                 home studio birth monsters statement
26        glimpse video century love thejawaanisong ❤ 🙏
27    % growth utility vehicle sales market share in...
28    outlook rupee month outcome month election exc...
29    analysts tally power feuds corruption allegati...
...                                                 ...
2718  party list candidates elections candidate plac...
2719                        moment people industry baby
2720  gold % % purities ₹34,180 gram prices jeweller...
2721                              users years teenagers
2722  states polling turnout % % % turnout % turnout...
2723  behaviour part behaviour individuals activitie...
2724                                             actors
2725       Telugu TV road accident place hours district
2726  week company developer conference system appoi...
2727                                              debut
2728  smartphone manufacturer today market base Note...
2729  world smartphone maker app models options app ...
2730  target price Q4FY19 margin bps QoQ margin bps ...
2731  Music world creation music consumer opportunit...
2732  initiation contempt proceedings chairman % day...
2733  hand hotel airline loyalty programmes stickine...
2734  government job electrification governments qua...
2735  basis points % yield basis point % yield % % %...
2736  Section advertising TV media period hours poll...
2737  techniques machines years experts networks lan...
2738  traffic challan payment cities services tab se...
2739  countries people gender age concept age term r...
2740  delivery fuel aircraft economics aircraft % da...
2741  fan critic rallies purpose elections nominees ...
2742  leaders suggestion people leaders suggestion b...
2743  researchers fraud channel years % artifice cha...
2744  camera setup camera depth segmentation photos ...
2745  camera setup aperture front selfie camera pric...
2746  gap revenue costs gap states study scheme powe...
2747  bank customers money people share market netwo...

[2748 rows x 1 columns]

In [537]:
from sklearn.model_selection import train_test_split

X = df['STORY']
y = df.iloc[:,].values

y=y.reshape(y.shape[0],1)
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features = [0])
y = onehotencoder.fit_transform(y).toarray()


IndexError: single positional indexer is out-of-bounds

In [ ]:
stopwords = ['a', 'about', 'above', 'across', 'after', 'afterwards', 'again', 'against', 'all', 'almost', 'alone', 'along', 'already', 'also', 'although', 'always', 'am', 'among', 'amongst', 'amoungst', 'amount', 'an', 'and', 'another', 'any', 'anyhow', 'anyone', 'anything', 'anyway', 'anywhere', 'are', 'around', 'as', 'at', 'back', 'be', 'became', 'because', 'become', 'becomes', 'becoming', 'been', 'before', 'beforehand', 'behind', 'being', 'below', 'beside', 'besides', 'between', 'beyond', 'bill', 'both', 'bottom', 'but', 'by', 'call', 'can', 'cannot', 'cant', 'co', 'con', 'could', 'couldnt', 'cry', 'de', 'describe', 'detail', 'do', 'done', 'down', 'due', 'during', 'each', 'eg', 'eight', 'either', 'eleven', 'else', 'elsewhere', 'empty', 'enough', 'etc', 'even', 'ever', 'every', 'everyone', 'everything', 'everywhere', 'except', 'few', 'fifteen', 'fifty', 'fill', 'find', 'fire', 'first', 'five', 'for', 'former', 'formerly', 'forty', 'found', 'four', 'from', 'front', 'full', 'further', 'get', 'give', 'go', 'had', 'has', 'hasnt', 'have', 'he', 'hence', 'her', 'here', 'hereafter', 'hereby', 'herein', 'hereupon', 'hers', 'herself', 'him', 'himself', 'his', 'how', 'however', 'hundred', 'i', 'ie', 'if', 'in', 'inc', 'indeed', 'interest', 'into', 'is', 'it', 'its', 'itself', 'keep', 'last', 'latter', 'latterly', 'least', 'less', 'ltd', 'made', 'many', 'may', 'me', 'meanwhile', 'might', 'mill', 'mine', 'more', 'moreover', 'most', 'mostly', 'move', 'much', 'must', 'my', 'myself', 'name', 'namely', 'neither', 'never', 'nevertheless', 'next', 'nine', 'no', 'nobody', 'none', 'noone', 'nor', 'not', 'nothing', 'now', 'nowhere', 'of', 'off', 'often', 'on', 'once', 'one', 'only', 'onto', 'or', 'other', 'others', 'otherwise', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 'part', 'per', 'perhaps', 'please', 'put', 'rather', 're', 'same', 'see', 'seem', 'seemed', 'seeming', 'seems', 'serious', 'several', 'she', 'should', 'show', 'side', 'since', 'sincere', 'six', 'sixty', 'so', 'some', 'somehow', 'someone', 'something', 'sometime', 'sometimes', 'somewhere', 'still', 'such', 'system', 'take', 'ten', 'than', 'that', 'the', 'their', 'them', 'themselves', 'then', 'thence', 'there', 'thereafter', 'thereby', 'therefore', 'therein', 'thereupon', 'these', 'they', 'thick', 'thin', 'third', 'this', 'those', 'though', 'three', 'through', 'throughout', 'thru', 'thus', 'to', 'together', 'too', 'top', 'toward', 'towards', 'twelve', 'twenty', 'two', 'un', 'under', 'until', 'up', 'upon', 'us', 'very', 'via', 'was', 'we', 'well', 'were', 'what', 'whatever', 'when', 'whence', 'whenever', 'where', 'whereafter', 'whereas', 'whereby', 'wherein', 'whereupon', 'wherever', 'whether', 'which', 'while', 'whither', 'who', 'whoever', 'whole', 'whom', 'whose', 'why', 'will', 'with', 'within', 'without', 'would', 'yet', 'you', 'your', 'yours', 'yourself', 'yourselves']

In [ ]:
import nltk
from nltk.stem import WordNetLemmatizer 
lemmatizer = WordNetLemmatizer()
import re
def Tokenizer(str_input):
    words = re.sub(r"[^A-Za-z0-9\-]", " ", str_input).lower().split()
    porter_stemmer=nltk.PorterStemmer()
    words = [lemmatizer.lemmatize(word) for word in words]
    return words

In [ ]:
from sklearn.model_selection import train_test_split
X = df['STORY']
y = df['SECTION']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
import nltk
nltk.download('wordnet')
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
text_clf_lsvc2 = Pipeline([('tfidf', TfidfVectorizer(tokenizer=Tokenizer,stop_words=stopwords)),('clf',  LinearSVC()),
])
text_clf_lsvc2.fit(X_train,y_train)

In [ ]:
from sklearn import metrics
predictions1 = text_clf_lsvc2.predict(X_test)
#predictions2 = text_clf_nb.predict(X_test)
print(metrics.confusion_matrix(y_test,predictions1))

In [ ]:
print(metrics.classification_report(y_test,predictions1))

In [ ]:
print(metrics.accuracy_score(y_test,predictions1))

In [ ]:
df = pd.read_csv('Data_Test.csv')
from sklearn.model_selection import train_test_split
X2 = df['STORY']

In [ ]:
for j in range(len(df)):
    n = [token for token in nlp(df['STORY'][j]) if token.pos_=='NOUN']
    text=''
    for i in range(len(n)):
        text=text+' '+str(n[i])
    text=text[1:]
    df['STORY'][j]=text
    print(j)
df.head()

In [529]:
text_clf_lsvc2.fit(X,y)

Pipeline(memory=None,
     steps=[('tfidf', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,...ax_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0))])

In [531]:
predictions = text_clf_lsvc2.predict(X2)
predictions

array([1, 2, 1, ..., 1, 0, 1], dtype=int64)

In [532]:
ans = pd.DataFrame({'SECTION': predictions})

In [533]:
writer = pd.ExcelWriter('latest.xlsx', engine='xlsxwriter')

# Convert the dataframe to an XlsxWriter Excel object.
ans.to_excel(writer, sheet_name='Sheet1')

# Close the Pandas Excel writer and output the Excel file.
writer.save()